- hosts: localhost
  roles:
    - gsoft.azure_devops_agent
  vars:
    - az_devops_agent_role: build
    - az_devops_accountname: gcpcluster2
    - az_devops_accesstoken: l2ildip6d2jdmuyarwkgkphb4bxrxrwdastrfs74avcvmbcnb54a
